db_path = "bot.db"
redirect_url = "https://t.me/PocketerBot/"

[messages]
    [messages.responses]
        start = "Привет! Чтобы использовать возможности бота (список доступных команд можно узнать введя команду /help), тебе необходимо предоставить мне доступ к твоему Pocket аккаунту. Для этого переходи по ссылке:\n%s"
        help = "Я могу выполнять такие действия, как:\n1. Добавление ссылки в твой Pocket. Для добавления достаточно отправить мне ссылку, а я ее сохраню\n2. Получение всех ссылок из твоего Pocket. Для этого воспользуйся командой /get\n3. Удаление ссылки по ID. Удаление можно воспроизвести командой /delete id, где id - идентификатор ссылки, который можно получить при помощи команды /get"
        already_authorized = "Ты уже авторизован, отправляй ссылку, а я её сохраню."
        saved_successfully = "Ссылка была успешно сохранена!"
        deleted_successfully = "Ссылка была успешно удалена!"
        unknown_command = "Я не знаю такой комманды."
    [messages.errors]
        default = "Произошла непредвиденная ошибка."
        invalid_url = "Это не ссылка!"
        unauthorized = "Ты не авторизован, используй команду /start для авторизации."
        failed_to_save = "Не удалось добавить ссылку в твой Pocket список, попробуй чуть позже."
        failed_to_get = "Не удалось получить ссылки из твоего списка, попробуй чуть позже."
        failed_to_delete = "Не удалось удалить ссылку, похоже, ее нет твоем списке."
        failed_to_authorized = "Мне не удалось тебя авторизоровать."
        failed_to_generate = "Не удалось создать авторизационную ссылку."
