db_path = "bot.db"
redirect_url = "https://t.me/PocketerBot/"

[messages]
    [messages.responses]
        start = "Привет! Чтобы сохранять ссылки в своем Pocket аккаунте или получить их, для начала тебе необходимо дать мне на это доступ. Для этого переходи по ссылке:\n%s"
        already_authorized = "Ты уже авторизован, отправляй ссылку, а я её сохраню."
        saved_successfully = "Ссылка была успешно сохранена!"
        unknown_command = "Я не знаю такой комманды."
    [messages.errors]
        default = "Произошла непредвиденная ошибка."
        invalid_url = "Это не ссылка!"
        unauthorized = "Ты не авторизован, используй команду /start для авторизации."
        failed_to_save = "Не удалось добавить ссылку в твой Pocket список, попробуй чуть позже."
        failed_to_get = "Не удалось получить ссылки из твоего списка, попробуй чуть позже."
        failed_to_authorized = "Мне не удалось тебя авторизоровать."
        failed_to_generate = "Не удалось создать авторизационную ссылку."
